apiVersion: v1
entries:
  gpu-provisioner:
  - apiVersion: v2
    appVersion: 0.4.1
    created: "2026-02-26T03:30:33.23164556Z"
    description: A Helm chart for gpu-provisioner
    digest: e3f9c1c986958c0b7acbc23b74df1db2e7ba65198bc9aa7331722d78f68bb8ce
    maintainers:
    - email: vrgf2003@gmail.com
      name: Fei-Guo
    - email: hebaelayoty@gmail.com
      name: helayoty
    name: gpu-provisioner
    sources:
    - https://github.com/Azure/gpu-provisioner
    type: application
    urls:
    - https://Azure.github.io/gpu-provisioner/charts/gpu-provisioner-0.4.1.tgz
    version: 0.4.1
  - apiVersion: v2
    appVersion: 0.4.0
    created: "2026-02-20T23:37:15.350906133Z"
    description: A Helm chart for gpu-provisioner
    digest: 57e5e79cbc986d9e8d8fbb78a3fcc84664a96b905ec0c94f20742a1e0751fe7b
    maintainers:
    - email: vrgf2003@gmail.com
      name: Fei-Guo
    - email: hebaelayoty@gmail.com
      name: helayoty
    name: gpu-provisioner
    sources:
    - https://github.com/Azure/gpu-provisioner
    type: application
    urls:
    - https://Azure.github.io/gpu-provisioner/charts/gpu-provisioner-0.4.0.tgz
    version: 0.4.0
  - apiVersion: v2
    appVersion: 0.3.8
    created: "2025-12-19T07:30:46.343567062Z"
    description: A Helm chart for gpu-provisioner
    digest: 05e9dbd9e5440236823b95d610b52b3b9c6b84f3b69a4f0d0dfe7804ca8e3d33
    maintainers:
    - email: vrgf2003@gmail.com
      name: Fei-Guo
    - email: hebaelayoty@gmail.com
      name: helayoty
    name: gpu-provisioner
    sources:
    - https://github.com/Azure/gpu-provisioner
    type: application
    urls:
    - https://Azure.github.io/gpu-provisioner/charts/gpu-provisioner-0.3.8.tgz
    version: 0.3.8
  - apiVersion: v2
    appVersion: 0.3.7
    created: "2025-10-18T04:25:03.151435442Z"
    description: A Helm chart for gpu-provisioner
    digest: f0c89752d4f73d31eba63f8bec0d64a0cd196ee92790a9265caf80e3c73f46b6
    maintainers:
    - email: vrgf2003@gmail.com
      name: Fei-Guo
    - email: hebaelayoty@gmail.com
      name: helayoty
    name: gpu-provisioner
    sources:
    - https://github.com/Azure/gpu-provisioner
    type: application
    urls:
    - https://Azure.github.io/gpu-provisioner/charts/gpu-provisioner-0.3.7.tgz
    version: 0.3.7
  - apiVersion: v2
    appVersion: 0.3.6
    created: "2025-09-21T09:38:32.406328233Z"
    description: A Helm chart for gpu-provisioner
    digest: 88c48caedb1322d108046bf9dd56371215dac312b10ebafde6a4ad93b036ea5e
    maintainers:
    - email: vrgf2003@gmail.com
      name: Fei-Guo
    - email: hebaelayoty@gmail.com
      name: helayoty
    name: gpu-provisioner
    sources:
    - https://github.com/Azure/gpu-provisioner
    type: application
    urls:
    - https://Azure.github.io/gpu-provisioner/charts/gpu-provisioner-0.3.6.tgz
    version: 0.3.6
  - apiVersion: v2
    appVersion: 0.3.5
    created: "2025-05-16T02:05:02.386028313Z"
    description: A Helm chart for gpu-provisioner
    digest: 886c6443a8fe259bc5adf42a4071f161b232033c40e6b43e6ff509743c667cb1
    maintainers:
    - email: vrgf2003@gmail.com
      name: Fei-Guo
    - email: hebaelayoty@gmail.com
      name: helayoty
    name: gpu-provisioner
    sources:
    - https://github.com/Azure/gpu-provisioner
    type: application
    urls:
    - https://Azure.github.io/gpu-provisioner/charts/gpu-provisioner-0.3.5.tgz
    version: 0.3.5
  - apiVersion: v2
    appVersion: 0.3.4
    created: "2025-05-15T02:22:21.347472205Z"
    description: A Helm chart for gpu-provisioner
    digest: 19b9a6e03aba489b347207ab85c687184e21aacc084244df094a46107f166447
    maintainers:
    - email: vrgf2003@gmail.com
      name: Fei-Guo
    - email: hebaelayoty@gmail.com
      name: helayoty
    name: gpu-provisioner
    sources:
    - https://github.com/Azure/gpu-provisioner
    type: application
    urls:
    - https://Azure.github.io/gpu-provisioner/charts/gpu-provisioner-0.3.4.tgz
    version: 0.3.4
  - apiVersion: v2
    appVersion: 0.3.3
    created: "2025-04-02T00:57:20.401787935Z"
    description: A Helm chart for gpu-provisioner
    digest: 15a920d1f1734b814c5c85562735f9d6b4903c38c86fae7c3a7e9c19bc277022
    maintainers:
    - email: vrgf2003@gmail.com
      name: Fei-Guo
    - email: hebaelayoty@gmail.com
      name: helayoty
    name: gpu-provisioner
    sources:
    - https://github.com/Azure/gpu-provisioner
    type: application
    urls:
    - https://Azure.github.io/gpu-provisioner/charts/gpu-provisioner-0.3.3.tgz
    version: 0.3.3
  - apiVersion: v2
    appVersion: 0.3.2
    created: "2025-03-06T04:24:57.494871579Z"
    description: A Helm chart for gpu-provisioner
    digest: 98b88aaf6dc7c2453322ec7b82e28b03ea30e5723e55299c31cba88d29e1c493
    maintainers:
    - email: vrgf2003@gmail.com
      name: Fei-Guo
    - email: hebaelayoty@gmail.com
      name: helayoty
    name: gpu-provisioner
    sources:
    - https://github.com/Azure/gpu-provisioner
    type: application
    urls:
    - https://Azure.github.io/gpu-provisioner/charts/gpu-provisioner-0.3.2.tgz
    version: 0.3.2
  - apiVersion: v2
    appVersion: 0.3.1
    created: "2025-01-15T02:28:04.542478681Z"
    description: A Helm chart for gpu-provisioner
    digest: d22d60d3bec3dd3c548a050b8287822af1e0d83a84f3dd0085e55bc8e8fc1442
    maintainers:
    - email: vrgf2003@gmail.com
      name: Fei-Guo
    - email: hebaelayoty@gmail.com
      name: helayoty
    name: gpu-provisioner
    sources:
    - https://github.com/Azure/gpu-provisioner
    type: application
    urls:
    - https://Azure.github.io/gpu-provisioner/charts/gpu-provisioner-0.3.1.tgz
    version: 0.3.1
  - apiVersion: v2
    appVersion: 0.3.0
    created: "2025-01-09T02:07:52.432753089Z"
    description: A Helm chart for gpu-provisioner
    digest: 401875c04fc9a4f110aa7f2ffa1db2cad2ed34cd248a665b07d07ec7e76e663c
    maintainers:
    - email: vrgf2003@gmail.com
      name: Fei-Guo
    - email: hebaelayoty@gmail.com
      name: helayoty
    name: gpu-provisioner
    sources:
    - https://github.com/Azure/gpu-provisioner
    type: application
    urls:
    - https://Azure.github.io/gpu-provisioner/charts/gpu-provisioner-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v2
    appVersion: 0.2.1
    created: "2024-11-01T18:44:33.382683182Z"
    description: A Helm chart for gpu-provisioner
    digest: 38e994cfdfe87a3fc3504effa6e81756ea14953983d56dea94b2f8e7b1b5a7c5
    maintainers:
    - email: vrgf2003@gmail.com
      name: Fei-Guo
    - email: hebaelayoty@gmail.com
      name: helayoty
    name: gpu-provisioner
    sources:
    - https://github.com/Azure/gpu-provisioner
    type: application
    urls:
    - https://Azure.github.io/gpu-provisioner/charts/gpu-provisioner-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v2
    appVersion: 0.2.0
    created: "2024-03-18T23:41:36.932133375Z"
    description: A Helm chart for gpu-provisioner
    digest: 2ca4b35e9ec28174e5d7f83d4d2324440e6e40caee6d40297a63584b5ced9f6d
    maintainers:
    - email: vrgf2003@gmail.com
      name: Fei-Guo
    - email: hebaelayoty@gmail.com
      name: helayoty
    name: gpu-provisioner
    sources:
    - https://github.com/Azure/gpu-provisioner
    type: application
    urls:
    - https://Azure.github.io/gpu-provisioner/charts/gpu-provisioner-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2023-11-06T16:30:52.572675427Z"
    description: A Helm chart for gpu-provisioner
    digest: 3a1a4a47af9aa3823ab191be938179edeaee658c1b8f8c25857ca46c2df22a73
    maintainers:
    - email: vrgf2003@gmail.com
      name: Fei-Guo
    - email: hebaelayoty@gmail.com
      name: helayoty
    name: gpu-provisioner
    sources:
    - https://github.com/Azure/gpu-provisioner
    type: application
    urls:
    - https://Azure.github.io/gpu-provisioner/charts/gpu-provisioner-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2023-10-31T01:27:54.398265645Z"
    description: A Helm chart for gpu-provisioner
    digest: f82a622fe53964f9de50dd0824cd9585e0e5060aaa9f77f08219439d23914f92
    maintainers:
    - email: vrgf2003@gmail.com
      name: Fei-Guo
    - email: hebaelayoty@gmail.com
      name: helayoty
    name: gpu-provisioner
    sources:
    - https://github.com/Azure/gpu-provisioner
    type: application
    urls:
    - https://Azure.github.io/gpu-provisioner/charts/gpu-provisioner-0.0.1.tgz
    version: 0.0.1
generated: "2026-02-26T03:30:33.230589262Z"
